import { v4 as uuidv4 } from "uuid";
export const cardData = [
  {
    id: uuidv4(),
    name: "Calliography",
    img: "images/b1.webp",
    color: "Black",
    category: "T-Shart",
    price: 550,
  },
  {
    id: uuidv4(),
    name: "Bicycle V1",
    img: "images/h4.webp",
    color: "Black",
    category: "Hoodie",
    price: 380,
  },
  {
    id: uuidv4(),
    name: "Life Is Beautiful",
    img: "images/w1.webp",
    color: "White",
    category: "T-Shart",
    price: 450,
  },
  {
    id: uuidv4(),
    name: "Royal Blue",
    img: "images/p1.jpg",
    category: "Polo",
    price: 650,
  },
  {
    id: uuidv4(),
    name: "Think Before Speak",
    img: "images/w2.webp",
    color: "White",
    category: "T-Shart",
    price: 350,
  },
  {
    id: uuidv4(),
    name: "OUBD",
    img: "images/b2.webp",
    color: "Black",
    category: "T-Shart",
    price: 520,
  },
  {
    id: uuidv4(),
    name: "City Life",
    img: "images/b3.webp",
    color: "Black",
    category: "T-Shart",
    price: 650,
  },

  {
    id: uuidv4(),
    name: "Be Kind",
    img: "images/h2.webp",
    color: "Black",
    category: "Hoodie",
    price: 550,
  },
  {
    id: uuidv4(),
    name: "Nature v2",
    img: "images/b4.webp",
    color: "Black",
    category: "T-Shart",
    price: 340,
  },
  {
    id: uuidv4(),
    name: "Kindness Is Free",
    img: "images/w4.webp",
    color: "White",
    category: "T-Shart",
    price: 580,
  },
  {
    id: uuidv4(),
    name: "Royal Blue",
    img: "images/p1.jpg",
    category: "Polo",
    price: 650,
  },
  {
    id: uuidv4(),
    name: "Polo – Rust",
    img: "images/p2.jpg",
    category: "Polo",
    price: 450,
  },
  {
    id: uuidv4(),
    name: " Turkish Blue",
    img: "images/p3.jpg",
    category: "Polo",
    price: 650,
  },
  {
    id: uuidv4(),
    name: "Royale Blue",
    img: "images/p4.jpg",
    category: "Polo",
    price: 350,
  },
  {
    id: uuidv4(),
    name: "I’m not old",
    img: "images/h8.webp",
    color: "Blue",
    category: "Hoodie",
    price: 580,
  },
  {
    id: uuidv4(),
    name: "Over Load",
    img: "images/h1.webp",
    color: "Black",
    category: "Hoodie",
    price: 460,
  },

  {
    id: uuidv4(),
    name: " Vacation",
    img: "images/h3.webp",
    color: "Black",
    category: "Hoodie",
    price: 480,
  },
  {
    id: uuidv4(),
    name: "Over Load",
    img: "images/w3.webp",
    color: "White",
    category: "T-Shart",
    price: 420,
  },
  {
    id: uuidv4(),
    name: "Bicycle V1",
    img: "images/h4.webp",
    color: "Black",
    category: "Hoodie",
    price: 380,
  },
  {
    id: uuidv4(),
    name: "Sajhbela",
    img: "images/h5.webp",
    color: "Blue",
    category: "Hoodie",
    price: 580,
  },
  {
    id: uuidv4(),
    name: "Bondho",
    img: "images/h6.webp",
    color: "Blue",
    category: "Hoodie",
    price: 590,
  },
  {
    id: uuidv4(),
    name: "Boipoka",
    img: "images/h7.webp",
    color: "Blue",
    category: "Hoodie",
    price: 650,
  },
];
